# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64

    working_directory: ~/blurhash

    steps:
      - checkout

      - run:
          name: install libffi
          command: |
            yum install -y libffi libffi-devel

      - run:
          name: compile wheels
          command: |
            for PYBIN in /opt/python/*mu/bin; do
              "${PYBIN}/python" setup.py bdist_wheel
            done

      - run:
          name: build external libraries into wheels
          command: |
            for wheel in dist/*.whl; do
              auditwheel repair "$wheel"
            done

      - run:
          name: install packages and test
          command: |
            for PYBIN in /opt/python/*mu/bin; do
              "${PYBIN}/pip" install blurhash-python --no-index -f wheelhouse
              "${PYBIN}/python" setup.py test
            done

