# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_x86_64:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64

    working_directory: ~/blurhash-python

    steps:
      - run:
          name: Install dependencies
          command: |
            yum install -y libffi libffi-devel zlib zlib-devel libjpeg libjpeg-devel git

      - checkout

      - run:
          name: Compile wheels and install dev requirements
          command: |
            for PYBIN in /opt/python/cp{27,34,35,36,37}-*/bin; do
              "${PYBIN}/pip" install tox pytest
              "${PYBIN}/pip" wheel . -w dist/
            done

      - run:
          name: Build external libraries into wheels
          command: |
            for wheel in dist/*-cp*-linux_*.whl; do
              auditwheel repair "$wheel"
            done

      - run:
          name: Install packages and test
          command: |
            for PYBIN in /opt/python/cp{27,34,35,36,37}-*/bin; do
              "${PYBIN}/pip" install blurhash-python --no-index -f dist
              "${PYBIN}/pytest"
            done

      - run:
          name: Create source distribution
          command: |
            /opt/python/cp37-cp37m/bin/python setup.py sdist

      - run:
          name: Install and test source distribution
          command: |
            /opt/python/cp37-cp37m/bin/pip uninstall -y blurhash-python
            /opt/python/cp37-cp37m/bin/pip install blurhash-python --no-index -f dist
            /opt/python/cp37-cp37m/bin/pytest

      - run:
          name: Copy artefacts
          command: |
            cp dist/blurhash_python-*-manylinux1_*.whl dist/

      - store_artifacts:
          path: dist

  build_i686:
    docker:
      - image: quay.io/pypa/manylinux1_i686

    working_directory: ~/blurhash-python

    steps:
      - run:
          name: Install dependencies
          command: |
            yum install -y libffi.i386 libffi-devel.i386 zlib zlib-devel libjpeg libjpeg-devel git

      - checkout

      - run:
          name: Compile wheels and install dev requirements
          command: |
            for PYBIN in /opt/python/cp{27,34,35,36,37}-*/bin; do
              "${PYBIN}/pip" install tox pytest
              "${PYBIN}/pip" wheel . -w dist/ --build-option -plinux_i686
            done

      - run:
          name: Build external libraries into wheels
          command: |
            for wheel in dist/*-cp*-linux_*.whl; do
              auditwheel repair "$wheel"
            done

      - run:
          name: Install packages and test
          command: |
            for PYBIN in /opt/python/cp{27,34,35,36,37}-*/bin; do
              "${PYBIN}/pip" install blurhash-python --no-index -f dist
              "${PYBIN}/pytest"
            done

      - run:
          name: Copy artefacts
          command: |
            mkdir dist/
            cp dist/blurhash_python-*-manylinux1_*.whl dist/

      - store_artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - build_i686:
          filters:
            tags:
              only: /^v.*/
      - build_x86_64:
          filters:
            tags:
              only: /^v.*/
