# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_x86_64:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64

    working_directory: ~/blurhash-python

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            yum install -y libffi libffi-devel zlib zlib-devel libjpeg libjpeg-devel

      - run:
          name: Compile wheels and install dev requirements
          command: |
            for PYBIN in /opt/python/cp{27,33,34,35,36}-*/bin; do
              "${PYBIN}/pip" install -r dev-requirements.txt
              "${PYBIN}/pip" wheel . -w wheelhouse/
            done

      - run:
          name: Build external libraries into wheels
          command: |
            for wheel in wheelhouse/blurhash_python-*.whl; do
              auditwheel repair "$wheel"
            done

      - run:
          name: Install packages and test
          command: |
            for PYBIN in /opt/python/cp{27,33,34,35,36}-*/bin; do
              "${PYBIN}/pip" install blurhash-python --no-index -f wheelhouse
              "${PYBIN}/pytest"
            done

      - run:
          name: Create source distribution
          command: |
            /opt/python/cp36-cp36m/bin/python setup.py sdist

      - run:
          name: Install and test source distribution
          command: |
            /opt/python/cp36-cp36m/bin/pip uninstall -y blurhash-python
            /opt/python/cp36-cp36m/bin/pip install blurhash-python --no-index -f dist
            /opt/python/cp36-cp36m/bin/pytest

      - run:
          name: Copy artefacts
          command: |
            cp wheelhouse/blurhash_python-*-manylinux1_*.whl dist/

      - store_artifacts:
          path: dist

  build_i686:
    docker:
      - image: quay.io/pypa/manylinux1_i686

    working_directory: ~/blurhash-python

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            yum install -y libffi.i386 libffi-devel.i386 zlib zlib-devel libjpeg libjpeg-devel

      - run:
          name: Compile wheels and install dev requirements
          command: |
            for PYBIN in /opt/python/cp{27,33,34,35,36}-*/bin; do
              "${PYBIN}/pip" install -r dev-requirements.txt
              "${PYBIN}/pip" wheel . -w wheelhouse/
            done

      - run:
          name: Build external libraries into wheels
          command: |
            for wheel in wheelhouse/blurhash_python-*.whl; do
              auditwheel repair "$wheel"
            done

      - run:
          name: Install packages and test
          command: |
            for PYBIN in /opt/python/cp{27,33,34,35,36}-*/bin; do
              "${PYBIN}/pip" install blurhash-python --no-index -f wheelhouse
              "${PYBIN}/pytest"
            done

      - run:
          name: Copy artefacts
          command: |
            cp wheelhouse/blurhash_python-*-manylinux1_*.whl dist/

      - store_artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - build_i686
      - build_x86_64
